 [{"details": {"abilities": [Array], "base_experience": 72, "forms": [Array], "game_indices": [Array], "height": 7, "held_items": [Array], "id": 11, "is_default": true, "location_area_encounters": "https://pokeapi.co/api/v2/pokemon/11/encounters", "moves": [Array], "name": "metapod", "order": 15, "past_abilities": [Array], "past_types": [Array], "species": [Object], "sprites": [Object], "stats": [Array], "types": [Array], "weight": 99}, "name": "metapod", "url": "https://pokeapi.co/api/v2/pokemon/11/"}, {"details": {"abilities": [Array], "base_experience": 198, "forms": [Array], "game_indices": [Array], "height": 11, "held_items": [Array], "id": 12, "is_default": true, "location_area_encounters": "https://pokeapi.co/api/v2/pokemon/12/encounters", "moves": [Array], "name": "butterfree", "order": 16, "past_abilities": [Array], "past_types": [Array], "species": [Object], "sprites": [Object], "stats": [Array], "types": [Array], "weight": 320}, "name": "butterfree", "url": "https://pokeapi.co/api/v2/pokemon/12/"}, {"details": {"abilities": [Array], "base_experience": 39, "forms": [Array], "game_indices": [Array], "height": 3, "held_items": [Array], "id": 13, "is_default": true, "location_area_encounters": "https://pokeapi.co/api/v2/pokemon/13/encounters", "moves": [Array], "name": "weedle", "order": 17, "past_abilities": [Array], "past_types": [Array], "species": [Object], "sprites": [Object], "stats": [Array], "types": [Array], "weight": 32}, "name": "weedle", "url": "https://pokeapi.co/api/v2/pokemon/13/"}, {"details": {"abilities": [Array], "base_experience": 72, "forms": [Array], "game_indices": [Array], "height": 6, "held_items": [Array], "id": 14, "is_default": true, "location_area_encounters": "https://pokeapi.co/api/v2/pokemon/14/encounters", "moves": [Array], "name": "kakuna", "order": 18, "past_abilities": [Array], "past_types": [Array], "species": [Object], "sprites": [Object], "stats": [Array], "types": [Array], "weight": 100}, "name": "kakuna", "url": "https://pokeapi.co/api/v2/pokemon/14/"}, {"details": {"abilities": [Array], "base_experience": 178, "forms": [Array], "game_indices": [Array], "height": 10, "held_items": [Array], "id": 15, "is_default": true, "location_area_encounters": "https://pokeapi.co/api/v2/pokemon/15/encounters", "moves": [Array], "name": "beedrill", "order": 19, "past_abilities": [Array], "past_types": [Array], "species": [Object], "sprites": [Object], "stats": [Array], "types": [Array], "weight": 295}, "name": "beedrill", "url": "https://pokeapi.co/api/v2/pokemon/15/"}, {"details": {"abilities": [Array], "base_experience": 50, "forms": [Array], "game_indices": [Array], "height": 3, "held_items": [Array], "id": 16, "is_default": true, "location_area_encounters": "https://pokeapi.co/api/v2/pokemon/16/encounters", "moves": [Array], "name": "pidgey", "order": 21, "past_abilities": [Array], "past_types": [Array], "species": [Object], "sprites": [Object], "stats": [Array], "types": [Array], "weight": 18}, "name": "pidgey", "url": "https://pokeapi.co/api/v2/pokemon/16/"}, {"details": {"abilities": [Array], "base_experience": 122, "forms": [Array], "game_indices": [Array], "height": 11, "held_items": [Array], "id": 17, "is_default": true, "location_area_encounters": "https://pokeapi.co/api/v2/pokemon/17/encounters", "moves": [Array], "name": "pidgeotto", "order": 22, "past_abilities": [Array], "past_types": [Array], "species": [Object], "sprites": [Object], "stats": [Array], "types": [Array], "weight": 300}, "name": "pidgeotto", "url": "https://pokeapi.co/api/v2/pokemon/17/"}, {"details": {"abilities": [Array], "base_experience": 216, "forms": [Array], "game_indices": [Array], "height": 15, "held_items": [Array], "id": 18, "is_default": true, "location_area_encounters": "https://pokeapi.co/api/v2/pokemon/18/encounters", "moves": [Array], "name": "pidgeot", "order": 23, "past_abilities": [Array], "past_types": [Array], "species": [Object], "sprites": [Object], "stats": [Array], "types": [Array], "weight": 395}, "name": "pidgeot", "url": "https://pokeapi.co/api/v2/pokemon/18/"}, {"details": {"abilities": [Array], "base_experience": 51, "forms": [Array], "game_indices": [Array], "height": 3, "held_items": [Array], "id": 19, "is_default": true, "location_area_encounters": "https://pokeapi.co/api/v2/pokemon/19/encounters", "moves": [Array], "name": "rattata", "order": 25, "past_abilities": [Array], "past_types": [Array], "species": [Object], "sprites": [Object], "stats": [Array], "types": [Array], "weight": 35}, "name": "rattata", "url": "https://pokeapi.co/api/v2/pokemon/19/"}, {"details": {"abilities": [Array], "base_experience": 145, "forms": [Array], "game_indices": [Array], "height": 7, "held_items": [Array], "id": 20, "is_default": true, "location_area_encounters": "https://pokeapi.co/api/v2/pokemon/20/encounters", "moves": [Array], "name": "raticate", "order": 27, "past_abilities": [Array], "past_types": [Array], "species": [Object], "sprites": [Object], "stats": [Array], "types": [Array], "weight": 185}, "name": "raticate", "url": "https://pokeapi.co/api/v2/pokemon/20/"}, {"details": {"abilities": [Array], "base_experience": 52, "forms": [Array], "game_indices": [Array], "height": 3, "held_items": [Array], "id": 21, "is_default": true, "location_area_encounters": "https://pokeapi.co/api/v2/pokemon/21/encounters", "moves": [Array], "name": "spearow", "order": 30, "past_abilities": [Array], "past_types": [Array], "species": [Object], "sprites": [Object], "stats": [Array], "types": [Array], "weight": 20}, "name": "spearow", "url": "https://pokeapi.co/api/v2/pokemon/21/"}, {"details": {"abilities": [Array], "base_experience": 155, "forms": [Array], "game_indices": [Array], "height": 12, "held_items": [Array], "id": 22, "is_default": true, "location_area_encounters": "https://pokeapi.co/api/v2/pokemon/22/encounters", "moves": [Array], "name": "fearow", "order": 31, "past_abilities": [Array], "past_types": [Array], "species": [Object], "sprites": [Object], "stats": [Array], "types": [Array], "weight": 380}, "name": "fearow", "url": "https://pokeapi.co/api/v2/pokemon/22/"}]
 WARN  SerializableStateInvariantMiddleware took 239ms, which is more than the warning threshold of 32ms.
If your state or actions are very large, you may want to disable the middleware as it might cause too much of a slowdown in development mode. See https://redux-toolkit.js.org/api/getDefaultMiddleware for instructions.
It is disabled in production builds, so you don't need to worry about that.















































































